(() => {
"use strict";
const TYPES=["steel","ember","tide","aether","bloom","void"];
const COLORS={steel:"#9fc8ff",ember:"#ff836f",tide:"#5ae5ff",aether:"#b783ff",bloom:"#72f0b4",void:"#ff65bc"};
const LABEL={steel:"ACERO",ember:"BRASA",tide:"MAREA",aether:"ÉTER",bloom:"BROTE",void:"VACÍO"};
const RELICS=[
 {id:"echo",name:"Forja de Eco",type:"steel",rarity:"ÉPICA",text:"Las cadenas de ACERO de 4+ repiten el 55% del daño."},
 {id:"ash",name:"Jardín de Ceniza",type:"ember",rarity:"RARÍSIMA",text:"BROTE carga a Lyra y su suprema también cura al grupo."},
 {id:"mirror",name:"Espejo de Marea",type:"tide",rarity:"ÉPICA",text:"El 35% del daño absorbido por barrera rebota al enemigo."},
 {id:"lens",name:"Lente del Vacío",type:"void",rarity:"LEGENDARIA",text:"VACÍO puede hacer crítico x2.4 y rompe escudo."},
 {id:"pulse",name:"Pulso de Éter",type:"aether",rarity:"ÉPICA",text:"ÉTER carga energía adicional a todo el escuadrón."},
 {id:"cascade",name:"Corazón de Cascada",type:"bloom",rarity:"LEGENDARIA",text:"Cada cascada aumenta el multiplicador de la resolución."},
 {id:"triune",name:"Juramento Trino",type:"aether",rarity:"CÓSMICA",text:"Las cadenas de 5+ cargan a todos y generan una onda de choque."},
 {id:"phoenix",name:"Hilo Fénix",type:"ember",rarity:"CÓSMICA",text:"El primer héroe caído revive con 45% de vida y lanza su suprema."}
];
const HEROES={
 kael:{name:"KAEL VOSS",role:"Vanguardia del Umbral",desc:"Especialista en Acero, ruptura y golpes encadenados.",max:110},
 lyra:{name:"LYRA SOL",role:"Tejedora de Ceniza",desc:"Daño explosivo, ignición y detonaciones de área.",max:92},
 nyx:{name:"NYX VALE",role:"Guardiana Astral",desc:"Barrera, curación y respuesta defensiva del escuadrón.",max:118}
};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sleep=ms=>new Promise(r=>setTimeout(r,ms)), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), rand=n=>Math.floor(Math.random()*n);
const settingsDefaults={audio:true,particles:true,shake:true,motion:false,quality:"Alta",volume:70,haptics:true,contrast:false,bigNumbers:false};
function loadJSON(k,d){try{return Object.assign({},d,JSON.parse(localStorage.getItem(k))||{});}catch{return {...d};}}
let settings=loadJSON("riftweave.settings",settingsDefaults), meta=loadJSON("riftweave.meta",{bestRoom:1,runs:0,shards:0,achievements:{}}), audio=null, toastTimer=0, currentScreen="home";
function fresh(){return{grid:[],selected:null,locked:false,room:1,turn:1,aether:0,sync:0,combo:1,bestChain:0,relics:[],partyShield:0,phoenixUsed:false,heroes:{kael:{hp:110,max:110,energy:0,alive:true},lyra:{hp:92,max:92,energy:0,alive:true},nyx:{hp:118,max:118,energy:0,alive:true}},enemy:{hp:300,max:300,shield:0,maxShield:0,countdown:3,boss:false,kind:"umbra",name:"DEVORADOR DE UMBRA",tier:"RIFT BEAST",enraged:false}}}
let state=fresh();
function saveSettings(){localStorage.setItem("riftweave.settings",JSON.stringify(settings));applySettings()}
function saveMeta(){localStorage.setItem("riftweave.meta",JSON.stringify(meta));updateMetaUI()}
function saveRun(){try{localStorage.setItem("riftweave.run",JSON.stringify(state));updateContinue()}catch{}}
function loadRun(){try{const s=JSON.parse(localStorage.getItem("riftweave.run"));if(!s?.grid?.length)return false;state=s;return true}catch{return false}}
function clearRun(){localStorage.removeItem("riftweave.run");updateContinue()}
function hasRelic(id){return state.relics.includes(id)}
function applySettings(){document.body.classList.toggle("reduce-motion",settings.motion);document.body.classList.toggle("high-contrast",settings.contrast);document.body.classList.toggle("big-numbers",settings.bigNumbers);document.body.classList.toggle("low-quality",settings.quality==="Baja");document.body.classList.toggle("medium-quality",settings.quality==="Media");if(audio)audio.master.gain.value=settings.audio?settings.volume/100*.26:0}
function initAudio(){if(audio)return;const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return;const ctx=new AC(),master=ctx.createGain();master.gain.value=settings.audio?settings.volume/100*.26:0;master.connect(ctx.destination);const filter=ctx.createBiquadFilter();filter.type="lowpass";filter.frequency.value=470;filter.connect(master);[55,82.4,110].forEach((f,i)=>{const o=ctx.createOscillator(),g=ctx.createGain();o.type=i===1?"sine":"triangle";o.frequency.value=f;g.gain.value=[.018,.012,.007][i];o.connect(g);g.connect(filter);o.start()});audio={ctx,master}}
function sfx(type,p=1){if(!settings.audio)return;initAudio();if(!audio)return;if(audio.ctx.state==="suspended")audio.ctx.resume();const cfg={click:[280,430,.05,"sine"],match:[420,850,.1,"triangle"],hit:[125,48,.14,"sawtooth"],cast:[340,1050,.21,"sine"],heal:[520,800,.23,"sine"],reward:[540,1200,.32,"triangle"],boss:[70,32,.32,"sawtooth"],fail:[180,65,.36,"sawtooth"]}[type]||[300,500,.08,"sine"];const {ctx,master}=audio,now=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain(),f=ctx.createBiquadFilter();o.type=cfg[3];o.frequency.setValueAtTime(cfg[0],now);o.frequency.exponentialRampToValueAtTime(Math.max(20,cfg[1]),now+cfg[2]);f.type="lowpass";f.frequency.value=2000;g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.07*p,now+.01);g.gain.exponentialRampToValueAtTime(.0001,now+cfg[2]);o.connect(f);f.connect(g);g.connect(master);o.start(now);o.stop(now+cfg[2]+.04)}
function haptic(pattern){if(settings.haptics&&navigator.vibrate)navigator.vibrate(pattern)}
function toast(t){const e=$("#toast");e.textContent=t;e.classList.add("show");clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove("show"),1800)}
function transition(name){const target=$("#"+name);if(!target)return;const tr=$("#transition");if(!settings.motion){tr.classList.remove("play");void tr.offsetWidth;tr.classList.add("play")}$$('.screen').forEach(s=>s.classList.remove('active'));target.classList.add('active');currentScreen=name;document.body.dataset.screen=name;document.body.classList.toggle('playing',name==='game');if(name!=="game")state.locked=false;updateNav();fit()}
function updateNav(){$$('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.screen===currentScreen))}
function fit(){document.documentElement.style.setProperty('--vh',`${innerHeight*.01}px`);requestAnimationFrame(()=>{document.body.offsetHeight;});toast("INTERFAZ AJUSTADA")}
async function fullscreen(){try{if(!document.fullscreenElement)await document.documentElement.requestFullscreen();else await document.exitFullscreen();setTimeout(fit,80)}catch{toast("PANTALLA COMPLETA NO DISPONIBLE")}}

function makeGrid(){const g=[];for(let i=0;i<49;i++){let t;do t=TYPES[rand(TYPES.length)];while((i%7>=2&&g[i-1]?.type===t&&g[i-2]?.type===t)||(i>=14&&g[i-7]?.type===t&&g[i-14]?.type===t));g.push({type:t,special:false})}state.grid=g}
function adjacent(a,b){const ar=Math.floor(a/7),ac=a%7,br=Math.floor(b/7),bc=b%7;return Math.abs(ar-br)+Math.abs(ac-bc)===1}
function findMatches(){const h=new Set();for(let r=0;r<7;r++){let st=0;for(let c=1;c<=7;c++){const p=state.grid[r*7+c-1]?.type,n=c<7?state.grid[r*7+c]?.type:null;if(n!==p){if(p&&c-st>=3)for(let k=st;k<c;k++)h.add(r*7+k);st=c}}}for(let c=0;c<7;c++){let st=0;for(let r=1;r<=7;r++){const p=state.grid[(r-1)*7+c]?.type,n=r<7?state.grid[r*7+c]?.type:null;if(n!==p){if(p&&r-st>=3)for(let k=st;k<r;k++)h.add(k*7+c);st=r}}}return h}
function tileSrc(t){return`assets/tile_${t.type}${t.special?'_special':''}.webp`}
function renderBoard(fall=false){const board=$("#board");board.innerHTML="";state.grid.forEach((t,i)=>{const b=document.createElement('button');b.className=`tile ${t.special?'special':''}${state.selected===i?' selected':''}${fall?' fall':''}`;b.dataset.i=i;b.innerHTML=`<img src="${tileSrc(t)}" alt="${LABEL[t.type]}${t.special?' especial':''}">`;b.onclick=()=>tileClick(i);board.appendChild(b)});board.style.pointerEvents=state.locked?'none':'auto'}
async function tileClick(i){if(state.locked)return;sfx('click',.4);if(state.selected===null){state.selected=i;renderBoard();return}if(state.selected===i){state.selected=null;renderBoard();return}if(!adjacent(state.selected,i)){state.selected=i;renderBoard();return}const a=state.selected;state.selected=null;state.locked=true;[state.grid[a],state.grid[i]]=[state.grid[i],state.grid[a]];renderBoard();await sleep(settings.motion?20:120);let m=findMatches();if(!m.size){[state.grid[a],state.grid[i]]=[state.grid[i],state.grid[a]];state.locked=false;renderBoard();toast("ESE MOVIMIENTO NO TEJE NINGUNA CADENA");return}state.turn++;state.enemy.countdown--;await resolveCascade(m);if(state.enemy.hp<=0){await roomClear();return}if(state.enemy.countdown<=0)await enemyAttack();state.locked=false;renderBoard();updateUI();saveRun()}
function drawLinks(matches){const svg=$("#linkFx");svg.innerHTML="";const board=$("#board"),br=board.getBoundingClientRect(),wr=$(".board-wrap").getBoundingClientRect();const pts=[...matches].map(i=>{const t=board.children[i].getBoundingClientRect();return[(t.left+t.width/2-wr.left)/wr.width*700,(t.top+t.height/2-wr.top)/wr.height*700]});pts.sort((a,b)=>a[0]+a[1]-b[0]-b[1]);if(pts.length>1){const p=document.createElementNS('http://www.w3.org/2000/svg','path');p.setAttribute('d','M '+pts.map(x=>x.join(' ')).join(' L '));svg.appendChild(p);setTimeout(()=>svg.innerHTML='',520)}}
async function resolveCascade(matches){let cascade=0;while(matches.size&&state.enemy.hp>0){cascade++;state.bestChain=Math.max(state.bestChain,cascade);state.combo=1+(cascade-1)*(.38+(hasRelic('cascade')?.26:0));state.sync=clamp(state.sync+matches.size*2.4+cascade*3,0,100);$("#chainText").textContent=cascade>1?`CADENA x${cascade}`:'CADENA LINK';$("#centerState").textContent=cascade>1?`CASCADA x${cascade}`:'MATCH';const tiles=$$('.tile');matches.forEach(i=>tiles[i]?.classList.add('match'));drawLinks(matches);sfx('match',clamp(.55+cascade*.12,.55,1.25));haptic(cascade>1?[12,18,20]:7);await sleep(settings.motion?35:260);const counts={},specials={};matches.forEach(i=>{const t=state.grid[i];counts[t.type]=(counts[t.type]||0)+1;if(t.special)specials[t.type]=(specials[t.type]||0)+1});await applyEffects(counts,specials,cascade);if(state.enemy.hp<=0)break;const arr=[...matches],keep=arr.length>=4?arr[0]:-1,keepType=keep>=0?state.grid[keep].type:null;matches.forEach(i=>state.grid[i]=null);if(keep>=0)state.grid[keep]={type:keepType,special:true};collapse();renderBoard(true);boardFlash(cascade);await sleep(settings.motion?25:220);matches=findMatches()}$("#centerState").textContent='LISTO';updateUI()}
function collapse(){for(let c=0;c<7;c++){const vals=[];for(let r=6;r>=0;r--){const v=state.grid[r*7+c];if(v)vals.push(v)}for(let r=6;r>=0;r--)state.grid[r*7+c]=vals[6-r]||{type:TYPES[rand(TYPES.length)],special:false}}}
async function applyEffects(c,spec,cascade){const mult=state.combo*(1+state.sync/250);if(c.steel){let d=Math.round(c.steel*7.5*mult*(1+(spec.steel||0)*.6));await heroStrike('kael',d,COLORS.steel);addEnergy('kael',c.steel*10);if(c.steel>=4&&hasRelic('echo')&&state.enemy.hp>0){await sleep(80);await heroStrike('kael',Math.round(d*.55),'#e8f5ff','ECO')}}if(c.ember&&state.enemy.hp>0){await heroStrike('lyra',Math.round(c.ember*7*mult*(1+(spec.ember||0)*.55)),COLORS.ember);addEnergy('lyra',c.ember*11)}if(c.tide){const n=Math.round(c.tide*5.7*(1+cascade*.12)*(1+(spec.tide||0)*.6));state.partyShield=Math.min(120,state.partyShield+n);addEnergy('nyx',c.tide*9);floatNum($('[data-hero="nyx"]'),`+${n} BARRERA`,COLORS.tide);burst($('[data-hero="nyx"]'),COLORS.tide,12)}if(c.bloom){heal(Math.round(c.bloom*4*(1+(spec.bloom||0)*.5)));addEnergy('nyx',c.bloom*7);if(hasRelic('ash'))addEnergy('lyra',c.bloom*8)}if(c.aether){const g=c.aether*(hasRelic('pulse')?15:8)*(1+(spec.aether||0)*.4);Object.keys(state.heroes).forEach(h=>addEnergy(h,g));state.aether+=c.aether+(spec.aether||0)*2;floatNum($("#board"),`+${c.aether} ÉTER`,COLORS.aether)}if(c.void&&state.enemy.hp>0){let d=Math.round(c.void*8.4*mult*(1+(spec.void||0)*.6)),lab='RUPTURA';if(hasRelic('lens')&&Math.random()<.35){d=Math.round(d*2.4);lab='CRÍTICO'}if(hasRelic('lens'))state.enemy.shield=Math.max(0,state.enemy.shield-12);damageEnemy(d,COLORS.void,lab)}if([...Object.values(c)].reduce((a,b)=>a+b,0)>=5&&hasRelic('triune')&&state.enemy.hp>0){Object.keys(state.heroes).forEach(h=>addEnergy(h,18));damageEnemy(24+state.room*2,'#fff0b0','ONDA TRINA');screenFlash()}for(const n of ['kael','lyra','nyx'])if(state.heroes[n].energy>=100&&state.heroes[n].alive&&state.enemy.hp>0)await ultimate(n,true)}
function addEnergy(n,v){const h=state.heroes[n];if(h.alive)h.energy=clamp(h.energy+v,0,100)}
function setHeroSprite(n,pose){const img=$("#"+n+"Sprite");if(!img)return;img.dataset.pose=pose;img.style.opacity=.72;setTimeout(()=>{img.src=`assets/${n}_${pose}.webp`;img.style.opacity=1},55)}
function combatFx(type,sourceName='kael'){
 const layer=$("#combatFxLayer"),battle=$(".battlefield");if(!layer||!battle)return;
 const br=battle.getBoundingClientRect(),src=sourceName==='enemy'?$("#enemySprite"):$('[data-hero="'+sourceName+'"] .sprite-wrap'),dst=sourceName==='enemy'?$('.party'):$("#enemySprite");
 if(!src||!dst)return;const a=src.getBoundingClientRect(),b=dst.getBoundingClientRect(),fx=document.createElement('i');
 fx.className='combat-fx '+type+' '+(type==='aether'?'pulse':'travel');
 const sx=a.left+a.width*.58-br.left,sy=a.top+a.height*.48-br.top,tx=(b.left+b.width*.48)-(a.left+a.width*.58),ty=(b.top+b.height*.48)-(a.top+a.height*.48);
 fx.style.left=sx+'px';fx.style.top=sy+'px';fx.style.setProperty('--tx',tx+'px');fx.style.setProperty('--ty',ty+'px');layer.appendChild(fx);setTimeout(()=>fx.remove(),720);
}
async function heroStrike(n,dmg,color,label=''){if(!state.heroes[n].alive||state.enemy.hp<=0)return;const u=$(`[data-hero="${n}"]`);setHeroSprite(n,'attack');u.classList.remove('attack');void u.offsetWidth;u.classList.add('attack');combatFx(n==='kael'?'slash':'fire',n);await sleep(settings.motion?20:140);damageEnemy(dmg,color,label||`-${dmg}`);burst($("#enemySprite"),color,15);sfx('hit',clamp(.65+dmg/110,.65,1.2));shake(dmg>35);setTimeout(()=>{u.classList.remove('attack');if(state.heroes[n].alive)setHeroSprite(n,'idle')},430)}
function damageEnemy(amount,color,label){let dmg=amount;if(state.enemy.shield>0){const b=Math.min(state.enemy.shield,dmg);state.enemy.shield-=b;dmg-=b}state.enemy.hp=Math.max(0,state.enemy.hp-dmg);const ez=$(".enemy-zone");ez.classList.remove('hit');void ez.offsetWidth;ez.classList.add('hit');floatNum($("#enemySprite"),label.startsWith('-')?label:`-${amount} ${label}`,color);if(state.enemy.boss&&!state.enemy.enraged&&state.enemy.hp/state.enemy.max<.42){state.enemy.enraged=true;state.enemy.tier='RIFT LORD · ENRAGED';setEnemySprite('enraged');toast('ARCONTE · FASE ENFURECIDA');sfx('boss',1.2)}updateUI()}
function setEnemySprite(pose='idle'){const img=$("#enemySprite");let src;if(state.enemy.boss)src=`assets/boss_${state.enemy.enraged&&pose==='idle'?'enraged':pose}.webp`;else src=`assets/${state.enemy.kind}_${pose}.webp`;img.style.opacity=.2;setTimeout(()=>{img.src=src;img.style.opacity=1},70)}
async function ultimate(n,auto=false){const h=state.heroes[n];if(!h.alive||h.energy<100&&!auto)return;h.energy=0;const u=$(`[data-hero="${n}"]`);setHeroSprite(n,'cast');u.classList.remove('cast');void u.offsetWidth;u.classList.add('cast');const col=n==='kael'?'#b8efff':n==='lyra'?'#ff78a0':'#85f3ca';combatFx(n==='kael'?'slash':n==='lyra'?'fire':'aether',n);burst(u,col,28);sfx('cast',1.15);toast(n==='kael'?'KAEL · FRACTURA VECTORIAL':n==='lyra'?'LYRA · SUPERNOVA DE CENIZA':'NYX · MANTO DE AURORA');await sleep(settings.motion?45:360);if(n==='kael'){state.enemy.shield=0;damageEnemy(48+state.room*3,col,'FRACTURA')}if(n==='lyra'){damageEnemy(40+state.room*2.4,col,'SUPERNOVA');if(hasRelic('ash'))heal(10)}if(n==='nyx'){state.partyShield=Math.min(140,state.partyShield+38);heal(14);floatNum(u,'AURORA +38',col)}screenFlash();haptic([18,18,30]);updateUI();setTimeout(()=>{u.classList.remove('cast');if(h.alive)setHeroSprite(n,'idle')},520)}
function heal(n){Object.entries(state.heroes).forEach(([k,h])=>{if(!h.alive)return;h.hp=clamp(h.hp+n,0,h.max);floatNum($(`[data-hero="${k}"]`),`+${n}`,COLORS.bloom)});sfx('heal',.7)}
async function enemyAttack(){if(state.enemy.hp<=0)return;state.enemy.countdown=state.enemy.boss?(state.enemy.enraged?1:2):3;$("#enemyIntent").textContent=state.enemy.boss?'ANIQUILACIÓN':'IMPACTO INMINENTE';setEnemySprite('attack');const ez=$(".enemy-zone");ez.classList.add('attack');combatFx('enemy','enemy');sfx(state.enemy.boss?'boss':'hit',1);await sleep(settings.motion?40:380);let base=Math.round(12+state.room*2.5+(state.enemy.boss?9:0)+(state.enemy.enraged?8:0));const absorbed=Math.min(state.partyShield,base);state.partyShield-=absorbed;base-=absorbed;if(absorbed&&hasRelic('mirror'))damageEnemy(Math.round(absorbed*.35),COLORS.tide,'REFLEJO');for(const [n,h] of Object.entries(state.heroes).filter(([,v])=>v.alive)){const d=Math.max(1,Math.round(base*(.78+Math.random()*.4)));h.hp=Math.max(0,h.hp-d);const u=$(`[data-hero="${n}"]`);setHeroSprite(n,'hurt');u.classList.add('hurt');floatNum(u,`-${d}`,'#ff6b82');if(h.hp<=0)await downHero(n);setTimeout(()=>{u.classList.remove('hurt');if(h.alive)setHeroSprite(n,'idle')},420)}shake(true);haptic([20,16,28]);await sleep(settings.motion?25:300);ez.classList.remove('attack');setEnemySprite('idle');$("#enemyIntent").textContent='PREPARANDO ATAQUE';updateUI();saveRun();if(Object.values(state.heroes).every(h=>!h.alive))await defeat()}
async function downHero(n){const h=state.heroes[n];if(hasRelic('phoenix')&&!state.phoenixUsed){state.phoenixUsed=true;h.hp=Math.round(h.max*.45);h.alive=true;h.energy=100;toast(`HILO FÉNIX · ${n.toUpperCase()} REGRESA`);await ultimate(n,true);return}h.alive=false;$(`[data-hero="${n}"]`).classList.add('down');toast(`${n.toUpperCase()} HA CAÍDO`)}
function makeEnemy(){const boss=state.room%5===0,kind=state.room%2===0?'glass':'umbra',info=kind==='glass'?['CUSTODIO DE VIDRIO','SENTINEL']:['DEVORADOR DE UMBRA','RIFT BEAST'],max=Math.round((210+state.room*78)*(boss?2.25:1)),shield=boss?Math.round(max*.15):(state.room>2?Math.round(max*.06):0);state.enemy={hp:max,max,shield,maxShield:shield,countdown:boss?2:3,boss,kind,name:boss?'ARCONTE DE LA GRIETA':info[0],tier:boss?'RIFT LORD · FASE I':info[1],enraged:false};setEnemySprite('idle');$("#objectiveText").textContent=boss?'Derrota al Arconte antes del colapso del Rift':`Rompe la defensa de ${state.enemy.name}`;updateUI()}
async function roomClear(){state.locked=true;$("#enemyIntent").textContent='FRACTURA ESTABILIZADA';sfx('reward',1.1);burst($("#enemySprite"),'#ffd580',38);boardFlash(4);state.aether+=10+state.room*2;meta.bestRoom=Math.max(meta.bestRoom,state.room);meta.shards+=3+Math.floor(state.room/2);saveMeta();saveRun();await sleep(settings.motion?80:650);showRelicChoices()}
function showRelicChoices(){const pool=RELICS.filter(r=>!state.relics.includes(r.id)).sort(()=>Math.random()-.5).slice(0,3);if(!pool.length){state.room++;nextRoom();return}const box=$("#relicChoices");box.innerHTML='';pool.forEach(r=>{const b=document.createElement('button');b.className='relic-choice';b.innerHTML=`<img src="assets/tile_${r.type}_special.webp"><small>${r.rarity}</small><b>${r.name}</b><p>${r.text}</p>`;b.onclick=()=>chooseRelic(r);box.appendChild(b)});openModal('relicModal')}
function chooseRelic(r){state.relics.push(r.id);closeModal('relicModal');sfx('reward',1);toast(`RELIQUIA · ${r.name.toUpperCase()}`);state.room++;state.sync=Math.max(0,state.sync-18);nextRoom()}
function nextRoom(){Object.values(state.heroes).forEach(h=>{if(h.alive)h.hp=Math.min(h.max,h.hp+Math.round(h.max*.14))});state.partyShield=Math.min(50,state.partyShield+10);makeEnemy();makeGrid();state.locked=false;renderBoard();renderRelics();updateUI();saveRun()}
function renderRelics(){const box=$("#runRelics");box.innerHTML='';state.relics.slice(-8).forEach(id=>{const r=RELICS.find(x=>x.id===id),d=document.createElement('div');d.className='relic-chip';d.title=r.name;d.innerHTML=`<img src="assets/tile_${r.type}_special.webp" style="width:100%;height:100%;object-fit:contain">`;box.appendChild(d)})}
function updateUI(){$("#hudRoom").textContent=String(state.room).padStart(2,'0');$("#hudAether").textContent=state.aether;$("#hudShards").textContent=meta.shards;$("#hudRelics").textContent=state.relics.length;$("#comboText").textContent=`x${state.combo.toFixed(2)}`;$("#syncBar").style.width=state.sync+'%';$("#turnLabel").textContent=`TURNO ${state.turn}`;$("#partyShield").textContent=state.partyShield;$("#forecastText").textContent=`${state.enemy.name} atacará en ${state.enemy.countdown} turno${state.enemy.countdown===1?'':'s'}.`;$("#enemyName").textContent=state.enemy.name;$("#enemyTier").textContent=state.enemy.tier;$("#enemyHp").style.width=(state.enemy.hp/state.enemy.max*100)+'%';$("#enemyShield").style.width=(state.enemy.maxShield?state.enemy.shield/state.enemy.maxShield*100:0)+'%';$("#enemyHpText").textContent=`${Math.ceil(state.enemy.hp)} / ${state.enemy.max}`;$("#enemyCountdown").textContent=`ATACA EN ${state.enemy.countdown}`;$("#objectiveBar").style.width=(1-state.enemy.hp/state.enemy.max)*100+'%';$("#pauseRoom").textContent=state.room;$("#pauseAether").textContent=state.aether;$("#pauseChain").textContent=state.bestChain;for(const [n,h] of Object.entries(state.heroes)){$("#"+n+"Hp").style.width=(h.hp/h.max*100)+'%';$("#"+n+"Energy").style.width=h.energy+'%';$("#"+n+"Ult").textContent=Math.round(h.energy)+'%';$$('[data-skill="'+n+'"]').forEach(ab=>{ab.classList.toggle('ready',h.energy>=100&&h.alive);ab.style.setProperty('--charge',Math.round(h.energy)+'%')})}renderRelics()}
function startRun(){initAudio();state=fresh();makeGrid();makeEnemy();renderBoard();$$('.unit').forEach(x=>x.classList.remove('down'));Object.keys(state.heroes).forEach(n=>setHeroSprite(n,'idle'));updateUI();saveRun();transition('game');toast('RIFT ABIERTO · TEJE TU PRIMERA CADENA');sfx('reward',.8)}
function continueRun(){if(!loadRun()){startRun();return}renderBoard();for(const [n,h] of Object.entries(state.heroes)){$(`[data-hero="${n}"]`).classList.toggle('down',!h.alive);setHeroSprite(n,'idle')}setEnemySprite('idle');updateUI();transition('game');toast('RUN RESTAURADA')}
async function defeat(){state.locked=true;renderBoard();sfx('fail',1);meta.runs++;meta.bestRoom=Math.max(meta.bestRoom,state.room);meta.shards+=Math.floor(state.room*1.5);saveMeta();clearRun();await sleep(settings.motion?40:450);$("#defeatSummary").textContent=`Rift ${state.room} · ${state.aether} Éter · Cascada máxima x${state.bestChain}`;openModal('defeatModal')}
function openModal(id){$("#"+id).classList.add('open')}function closeModal(id){$("#"+id).classList.remove('open')}
function floatNum(target,text,color){const r=target.getBoundingClientRect(),d=document.createElement('div');d.className='float-num';d.textContent=text;d.style.color=color;d.style.left=(r.left+r.width/2-30)+'px';d.style.top=(r.top+r.height*.35)+'px';$("#fx").appendChild(d);setTimeout(()=>d.remove(),900)}
function burst(target,color,count=14){if(!settings.particles)return;const r=target.getBoundingClientRect(),cx=r.left+r.width/2,cy=r.top+r.height/2,n=settings.quality==='Baja'?Math.ceil(count/3):settings.quality==='Media'?Math.ceil(count/2):count;for(let i=0;i<n;i++){const p=document.createElement('i');p.className='particle';p.style.color=color;p.style.left=cx+'px';p.style.top=cy+'px';const a=Math.random()*Math.PI*2,dist=25+Math.random()*90;p.style.setProperty('--dx',Math.cos(a)*dist+'px');p.style.setProperty('--dy',Math.sin(a)*dist+'px');$("#fx").appendChild(p);setTimeout(()=>p.remove(),720)}}
function boardFlash(){const e=$("#boardFlash");e.classList.remove('show');void e.offsetWidth;e.classList.add('show')}
function screenFlash(){const d=document.createElement('div');d.className='screen-flash flash-now';document.body.appendChild(d);setTimeout(()=>d.remove(),200)}
function shake(strong=false){if(settings.motion||!settings.shake)return;const a=$("#app");a.animate([{transform:'translate(0)'},{transform:'translate(3px,-2px)'},{transform:'translate(-3px,2px)'},{transform:'translate(0)'}],{duration:240});if(strong)haptic([16,14,24])}
function updateContinue(){let s=null;try{s=JSON.parse(localStorage.getItem('riftweave.run'))}catch{};$("#continueBtn").classList.toggle('hidden',!s);if(s)$("#continueMeta").textContent=`RIFT ${String(s.room).padStart(2,'0')} · TURNO ${s.turn}`}
function updateMetaUI(){$("#bestRoom").textContent=meta.bestRoom;$("#runsCount").textContent=meta.runs;$("#metaShards").textContent=meta.shards;$("#hudShards").textContent=meta.shards}
function populateInfo(){const hc=$("#heroCards");hc.innerHTML='';Object.entries(HEROES).forEach(([id,h])=>{const a=document.createElement('article');a.className='hero-card';a.innerHTML=`<div class="art"><img src="assets/${id}_idle.webp"></div><div class="copy"><small>${h.role}</small><h3>${h.name}</h3><p>${h.desc}</p><p><b>HP ${h.max}</b> · Suprema al 100% de energía · Sinergias específicas por tipo de ficha.</p></div>`;hc.appendChild(a)});const rc=$("#relicCollection");rc.innerHTML='';RELICS.forEach(r=>{const d=document.createElement('article');d.className='collection-card';d.innerHTML=`<img src="assets/tile_${r.type}_special.webp" style="width:58px;height:58px;object-fit:contain;float:left;margin-right:10px"><small style="color:var(--gold)">${r.rarity}</small><b>${r.name}</b><p>${r.text}</p>`;rc.appendChild(d)});$("#codexGrid").innerHTML=`<article class="codex-card visual"><img src="assets/umbra_idle.webp"><div><b>DEVORADOR DE UMBRA</b><p>Entidad del Vacío. Ataque directo y presión constante.</p></div></article><article class="codex-card visual"><img src="assets/glass_idle.webp"><div><b>CUSTODIO DE VIDRIO</b><p>Centinela cristalino con escudo y ataques perforantes.</p></div></article><article class="codex-card visual"><img src="assets/boss_idle.webp"><div><b>ARCONTE DE LA GRIETA</b><p>Boss de cada quinto Rift. Entra en fase enfurecida al 42% de vida.</p></div></article><article class="codex-card"><b>CADENAS</b><p>3 fichas activan el efecto base. 4+ generan una ficha potenciada. Las cascadas multiplican Sincronía y daño.</p></article><article class="codex-card"><b>SUPREMAS</b><p>Las fichas cargan energía según afinidad. Al llegar a 100%, puedes activar la habilidad del héroe.</p></article><article class="codex-card"><b>RELIQUIAS</b><p>Cada fractura estabilizada ofrece anomalías que cambian reglas y permiten builds emergentes.</p></article>`;$("#achievementGrid").innerHTML=[['PRIMERA FRACTURA','Completa tu primer Rift.'],['CASCADA V','Alcanza una cascada x5.'],['SINCRONÍA TOTAL','Lleva Sincronía al 100%.'],['ARCONTE CAÍDO','Derrota a un boss.'],['ARQUITECTO DE BUILDS','Reúne 5 reliquias en una run.'],['RIFT X','Alcanza el Rift 10.']].map((x,i)=>`<article class="collection-card"><small style="color:var(--cyan)">${i<2?'DESCUBRIBLE':'DESAFÍO'}</small><b>${x[0]}</b><p>${x[1]}</p></article>`).join('')}
async function endTurn(){if(currentScreen!=='game'||state.locked)return;state.locked=true;state.turn++;state.enemy.countdown--;$("#centerState").textContent='TURNO CERRADO';if(state.enemy.countdown<=0)await enemyAttack();state.locked=false;renderBoard();updateUI();saveRun()}
function bind(){$$('[data-screen]').forEach(b=>b.addEventListener('click',()=>transition(b.dataset.screen)));$("#newRunBtn").onclick=startRun;const end=$("#endTurnBtn");if(end)end.onclick=endTurn;$("#continueBtn").onclick=continueRun;$("#fitBtn").onclick=fit;$("#fullscreenBtn").onclick=fullscreen;$("#settingsFit").onclick=fit;$("#settingsFullscreen").onclick=fullscreen;$("#pauseBtn").onclick=()=>{state.locked=true;renderBoard();openModal('pauseModal')};$("#resumeBtn").onclick=()=>{closeModal('pauseModal');state.locked=false;renderBoard()};$("#pauseSettings").onclick=()=>{closeModal('pauseModal');transition('settings')};$("#pauseFit").onclick=fit;$("#abandonBtn").onclick=()=>{closeModal('pauseModal');defeat()};$("#retryBtn").onclick=()=>{closeModal('defeatModal');startRun()};$("#defeatHome").onclick=()=>{closeModal('defeatModal');transition('home')};$$('.ability').forEach(b=>b.onclick=()=>{const n=b.dataset.skill;if(state.heroes[n].energy>=100&&!state.locked)ultimate(n);else toast('HABILIDAD AÚN NO CARGADA')});addEventListener('keydown',e=>{if(currentScreen!=='game')return;const m={q:'kael',w:'lyra',e:'nyx'}[e.key.toLowerCase()];if(m&&state.heroes[m].energy>=100&&!state.locked)ultimate(m);if(e.key==='Escape')openModal('pauseModal')});const map={optParticles:'particles',optShake:'shake',optMotion:'motion',optAudio:'audio',optHaptics:'haptics',optContrast:'contrast',optBigNumbers:'bigNumbers'};Object.entries(map).forEach(([id,k])=>{const x=$("#"+id);x.checked=!!settings[k];x.onchange=()=>{settings[k]=x.checked;saveSettings()}});$("#optQuality").value=settings.quality;$("#optQuality").onchange=e=>{settings.quality=e.target.value;saveSettings()};$("#optVolume").value=settings.volume;$("#optVolume").oninput=e=>{settings.volume=+e.target.value;saveSettings()};$("#resetSave").onclick=()=>{if(confirm('¿Reiniciar todo el progreso local de RIFTWEAVE?')){localStorage.removeItem('riftweave.run');localStorage.removeItem('riftweave.meta');meta={bestRoom:1,runs:0,shards:0,achievements:{}};updateMetaUI();updateContinue();toast('PROGRESO LOCAL REINICIADO')}};addEventListener('resize',fit);document.addEventListener('fullscreenchange',fit)}
function stars(){const c=$("#stars"),ctx=c.getContext('2d');let pts=[];function resize(){const d=Math.min(devicePixelRatio||1,2);c.width=innerWidth*d;c.height=innerHeight*d;c.style.width=innerWidth+'px';c.style.height=innerHeight+'px';ctx.setTransform(d,0,0,d,0,0);pts=Array.from({length:Math.min(140,Math.floor(innerWidth*innerHeight/8500))},()=>({x:Math.random()*innerWidth,y:Math.random()*innerHeight,r:.3+Math.random()*1.1,s:.03+Math.random()*.12,a:.1+Math.random()*.45}))}function draw(t){ctx.clearRect(0,0,innerWidth,innerHeight);for(const p of pts){if(!settings.motion)p.y+=p.s;if(p.y>innerHeight+3)p.y=-3;ctx.globalAlpha=p.a*(.7+.3*Math.sin(t*.001+p.x));ctx.fillStyle='#c9edff';ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;requestAnimationFrame(draw)}addEventListener('resize',resize);resize();requestAnimationFrame(draw)}
document.body.dataset.screen='home';applySettings();populateInfo();bind();stars();updateMetaUI();updateContinue();makeGrid();makeEnemy();renderBoard();updateUI();fit();
})();